# Generated by Django 5.0.2 on 2024-03-06 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
