# Generated by Django 5.0.2 on 2024-03-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quiz_end_quiz_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='end',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='start',
            new_name='starttime',
        ),
    ]
