# Generated by Django 5.0.2 on 2024-03-09 04:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_end_quiz_endtime_rename_start_quiz_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
